comments/urls.py
from django.urls import path, include
from .views import (
	post_comment, comments_list, delete_comment
)

urlpatterns = [
	path('comments/<int:post_id>', comments_list, name='comments'),
	path('comment/delete/<int:comment_id>', delete_comment, name='comment-delete'),
	# comment on post
	path('post-comment/<int:post_id>/', post_comment, name='post_comment'),
	# comment reply
	path('post-comment/<int:post_id>/<int:parent_comment_id>/', post_comment, name='comment_reply'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path(r'admin/', admin.site.urls),
  path(r'', include('papers.urls')),
  path(r'', include('posts.urls')),
  path(r'', include('users.urls')),
  path(r'', include('comments.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, include
from .views import (
	PostList, PostDetail, UserPostList, PostCreate, 
	PostUpdate, PostDelete, PostBookmark, UserBookmarkPostList,
	tag_follow_toggle, TagPostList,
)

urlpatterns = [
	path('', PostList.as_view(extra_context={'home_page' : 'active'}), name='home'),
	path('ajax/bookmark/', PostBookmark.as_view(), name='bookmark'), # toggle bookmark
	path('posts/bookmark/<str:username>/', UserBookmarkPostList.as_view(extra_context={'bookmark_page' : 'active'}), name='user-bookmarked-posts'),
	path('posts/<str:username>/', UserPostList.as_view(), name='user-posts'), # all post by user
	path('post/new/', PostCreate.as_view(extra_context={'new_post_page' : 'active'}), name='post-create'), # create new post
	path('post/<int:pk>/', PostDetail.as_view(), name='post-detail'),	# a single post
  path('post/<int:pk>/update/', PostUpdate.as_view(), name='post-update'), # update this post
  path('post/<int:pk>/delete/', PostDelete.as_view(), name='post-delete'), # delete this post
  path('tag/<slug:tag_slug>/', TagPostList.as_view() , name='tag-posts'),
  path('tag/<int:pk>/follow', tag_follow_toggle, name='tag-follow'),	# check, toggle
  # hit counter for counting views
  path('hitcount/', include('hitcount.urls', namespace='hitcount')),
]

comments/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model, get_user
from mptt.models import MPTTModel, TreeForeignKey
from posts.models import Post

User = get_user_model()

# Create your models here.
class Comment(MPTTModel):
	parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
	reply_to = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='replyers')
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
	comment = models.TextField('comment', max_length=1000)
	created = models.DateTimeField('created', default = timezone.now)

	class MPTTMeta:
		order_insertion_by = ['created']

	def __str__(self):
		return f'{self.user.username}' + ' : ' + f'{self.comment[:20]}'

	# def get_absolute_url(self):

comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['comment']

comments/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.views.generic import (
	UpdateView,
	DeleteView
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import CommentForm
from .models import Comment
from posts.models import Post

# Create your views here.
@login_required
# New parameter parent_comment_id
def post_comment(request, post_id, parent_comment_id=None):
    post = get_object_or_404(Post, id=post_id)

    if request.method == 'POST':
      comment_form = CommentForm(request.POST)
      if comment_form.is_valid():
        new_comment = comment_form.save(commit=False)
        new_comment.post = post
        new_comment.user = request.user

        # Secondary response
        if parent_comment_id:
          parent_comment = Comment.objects.get(id=parent_comment_id)
          # If the response level exceeds level 2, it will be converted to level 2.
          new_comment.parent_id = parent_comment.get_root().id
          # Respondent
          new_comment.reply_to = parent_comment.user
          new_comment.save()
          return HttpResponse('200 OK')
          # return render(request, 'comments/comment_reply.html', context)
        else:
          new_comment.save()
          return HttpResponse('200 OK')
          # return render(request, 'comments/post_comment.html', context)
      else:
        return HttpResponse ("Invalid comment.")
    elif request.method == 'GET':
      comment_form = CommentForm()
      context = {
        'comment_form': comment_form,
        'post_id': post_id,
        'parent_comment_id': parent_comment_id,
      }
      return render(request, 'comments/comment_form.html', context)
    else:
      return HttpResponse ("Only GET/POST requests are accepted. ")


def comments_list(request, post_id):
  if request.method == 'GET':
    context = {
      'post_id' : post_id,
      'comments' : Comment.objects.filter(post__id = post_id),
    }
    # print(context['comments'])
  return render(request, 'comments/comment_list.html', context)


@login_required
def delete_comment(request, comment_id):
  if request.method == 'POST':
    try:
      comment = Comment.objects.get(pk = comment_id)
      if not comment:
        return HttpResponse('Not a valid comment')
      elif request.user != comment.user:
        return HttpResponse('You are not authorized to perform this action.')
      else:
        comment.delete()
        return HttpResponse('200 OK')
    except Exception as error:
      raise error
  else:
    return HttpResponse('Not a valid request.')


# @login_required
# def update_comment(request, comment_id):
#   if request.method == 'POST':
#     try:
#       comment = Comment.objects.get(pk = comment_id)
#       if not comment:
#         return HttpResponse('Not a valid comment')
#       elif request.user != comment.user:
#         return HttpResponse('You are not authorized to perform this action.')
#       else:
#         comment_form = CommentForm(request.POST)
#         comment.comment = comment_form.cleaned_data['comment']
#         comment.save()
#         return HttpResponse('200 OK')
#     except Exception as error:
#       raise error
#   else:
#     return HttpResponse('Not a valid request.')

comments/templates/comments/comment_detail.html
<div class="container mb-2" id="comment-{{comment.pk}}">
	<div class="row">
		<div class="mr-auto">
			<strong>&#64;<a href="{% url 'profile' comment.user.username %}">{{comment.user.username}}</a></strong>
		</div>
		<div class="row text-right">
			<!-- delete -->
			{% if comment.user == user %}
			<div class="ml-2" style="cursor: pointer;" data-toggle="modal" data-target="#comment-delete-modal"
				onclick="load_delete_comment_modal('{{comment.comment}}', '{{comment.pk}}', '{% url 'comment-delete' comment.pk %}')">
				<i class="fa fa-trash"></i>
			</div>
			{% endif %}
		</div>
	</div>
	<div class="row">
		<div class="col">
			<p class="mb-0">
				{% if comment.reply_to %}
					<strong>&#64;<a href="{% url 'profile' comment.reply_to.username %}">{{comment.reply_to.username}}</a></strong>
				{% endif %}
				{{comment.comment}}
			</p>
		</div>
	</div>
	<div class="row">
		<!-- date -->
		<div class="ml-3 mr-2">
			<small class="text-muted">{{comment.created | date:"d M y h:i A" }}</small>
		</div>
		<!-- reply -->
		{% if user.is_authenticated %}
			<div class="text-left" style="cursor:pointer;" data-toggle="modal" data-target="#comment-modal"
				onclick="load_modal('{% url 'comment_reply' post_id comment.pk %}', '{{comment.user.username}}')">
			  <span class="badge badge-secondary">reply</span>
			</div>
		{% endif %}
	</div>
</div>

comments/templates/comments/comment_form.html
{% load crispy_forms_tags %}
<form action="." method="POST" id="reply_form" >
  {% csrf_token %}
  <div class="form-group">
    {{ comment_form | crispy }}
  </div>
</form>
<!-- reply to a comment -->
{% if parent_comment_id %}
  <button id="comment-reply" onclick = "post_comment('{% url 'comment_reply' post_id parent_comment_id %}')" class = "btn btn-primary"> send </button>
<!-- new comment -->
{% else %}
  <button id="comment-reply" onclick = "post_comment('{% url 'post_comment' post_id %}')" class = "btn btn-primary"> send </button>
{% endif %}

<script>
  function post_comment(url){
    let content = $('#id_comment').val();
    console.log(content);
    $.ajax({
      url: url,
      type: 'POST',
      data: {comment: content},
      headers: {'X-CSRFToken': '{{ csrf_token }}'},
      success: function(res){
        console.log(res);
        if(res === '200 OK'){
          // console.log(parent.location);
          parent.location.reload();
          // parent.append(comment);
        }
      }
    });
  }
</script>

comments/templates/comments/comment_list.html
{% load mptt_tags %}

<div class="container">
	{% if comments %}
		{% recursetree comments %}
			{% with comment=node %}
				{% include 'comments/comment_detail.html' %}
				{% if not comment.is_leaf_node %}
	        <div class="children ml-5">
	          {{ children }}
	        </div>
		    {% endif %}
			{% endwith %}
		{% endrecursetree %}
	{% else %}
		<div class="h4 d-flex justify-content-center">
			<p>No Comments</p>
		</div>
	{% endif %}
	<!-- Comment Post Modal -->
	<div class="modal fade" id="comment-modal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="CommentModalLabel">Add a comment</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <!-- actual form for comment -->
	      <div class="modal-body" id="modal-body">
	      </div>
	    </div>
	  </div>
	</div>
	<!-- Comment Delete modal -->
	<div class="modal fade" id="comment-delete-modal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="CommentDeleteModalLabel">Delete comment</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <!-- actual form for comment -->
	      <div class="modal-body" id="modal-delete-body">
	      </div>
	    </div>
	  </div>
	</div>
</div>

<script>
	function load_modal(url, commentUser=null) {
		let modal_body = $('#modal-body');
		let modal_title = $('#CommentModalLabel');
		if(commentUser)
			modal_title.html('Reply to @' + commentUser + ' comment');
		else
			modal_title.html('Add a comment');
		// console.log(url);
		modal_body.load(url);
	}

	function load_delete_comment_modal(comment, comment_id, url) {
		let modal_body = $('#modal-delete-body');
		let content = `
			<div class="modal-body" id="modal-delete-body">
				<strong>Are you sure want to delete this comment?</strong>
				<p>` + comment + `</p>
				<button class="btn btn-outline-danger" onclick="delete_comment('${comment_id}', '${url}')">
					Yes, Delete
				</button>
			</div>`;
		// console.log('delete' + url);
		modal_body.replaceWith(content);
	}

	function delete_comment(comment_id, url) {
		$.ajax({
	      url: url,
	      type: 'POST',
	      data: {'operation': 'delete comment'},
	      headers: {'X-CSRFToken': '{{ csrf_token }}'},
	      success: function(res){
	        // console.log(res);
	        if(res === '200 OK'){
	        	$('#comment-' + comment_id).replaceWith('<div class="col"><strong>Comment Deleted</strong><div>');
	        }
	      }
	    });
	}
</script>